name: build-my-book
on: [push]
jobs:
  build:
    env:
      TOKEN: ${{ secrets.TOKEN }}
      REF: github.com/${{github.repository}}
      MYEMAIL: 1312560006@qq.com
      MYNAME: ${{github.repository_owner}}        

    runs-on: ubuntu-latest
    steps:
    

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 10.x

      - name: install gitbook 
        run: |
          npm install -g gitbook-cli
          gitbook --version 

      - name: build gitbook
        run: |
          gitbook init
          gitbook build

      - name: push all files to master branch
        run: |
          git config --global user.email "${MYEMAIL}"
          git config --global user.name "${MYNAME}"
          git add .
          git commit -m "commited by GitHub workflow, built git book"
          git push --force "https://${TOKEN}@${REF}"
  
      - name: Sync repo to Gitee
        run: |
          git pull "https://${TOKEN}@${REF}" master:master
          git remote add GiteeBlogBook https://${{ secrets.GITEE_USER_NAME }}:${{ secrets.GITEE_TOKEN }}@gitee.com/${{ secrets.GITEE_USER_NAME }}/BlogBook.git
          git push --force GiteeBlogBook master:master
