name: build-my-book
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 安装nodejs（v12）
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 10.x
    # 安装gitbook
      - run: |
          npm install -g gitbook-cli
          gitbook --version 
    #gitbook初始化、构建 
      - run: |
          gitbook init
          gitbook build

      - name: push _book to branch gh-pages 
        env:
          TOKEN: ${{ secrets.TOKEN }}
          REF: github.com/${{github.repository}}
          MYEMAIL: 1312560006@qq.com                  # ！！记得修改为自己github设置的邮箱
          MYNAME: ${{github.repository_owner}}          
        run: |
          git add .
          git commit -m "commited by GitHub workflow, built git book"
          git push --force "https://${TOKEN}@${REF}"